#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Docker Compose Startup Issue Fix

set -e

echo "========================================"
echo "Docker Compose Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=60
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# Check if Docker is running
if ! docker info >/dev/null 2>&1; then
    echo -e "${RED}Error: Docker is not running. Please start Docker and try again.${NC}"
    exit 1
fi

# Check if docker-compose is available
if ! command -v docker-compose &> /dev/null; then
    echo -e "${RED}Error: docker-compose is not installed. Please install docker-compose and try again.${NC}"
    exit 1
fi

echo ""
echo "Building Docker images..."
docker-compose build --no-cache

echo ""
echo "Starting services..."
docker-compose up -d

echo ""
echo "Waiting for services to be ready..."

# Wait for PostgreSQL
wait_for_service 5432 "PostgreSQL"

# Wait for Keycloak
wait_for_service 8080 "Keycloak"

# Wait for Backend
wait_for_service 8000 "Backend API"

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:     http://localhost:8000"
echo "  API Documentation: http://localhost:8000/docs"
echo "  Health Check:     http://localhost:8000/health"
echo "  PostgreSQL:       localhost:5432"
echo "  Keycloak:         http://localhost:8080"
echo "  Prometheus:       http://localhost:9090"
echo "  Grafana:          http://localhost:3001"
echo ""
echo "View logs with: docker-compose logs -f"
echo "Stop services with: docker-compose down"
echo ""
