#!/bin/bash

# Auto-Build Environment Setup
# Demo Ordering Interface - Frontend + Backend
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Demo Ordering Interface"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${BLUE}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PRE-REQUISITES
# ============================================

echo -e "\n${BLUE}Checking pre-requisites...${NC}"

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python 3 not found. Please install Python 3.12+${NC}"
    exit 1
fi

if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js 18+${NC}"
    exit 1
fi

echo -e "${GREEN}Pre-requisites met${NC}"

# ============================================
# BACKEND SERVICE
# ============================================

echo -e "\n${BLUE}========================================${NC}"
echo -e "${BLUE}Starting Backend Service${NC}"
echo -e "${BLUE}========================================${NC}"

# Check if virtual environment exists
if [ ! -d "venv" ]; then
    echo -e "${YELLOW}Creating virtual environment...${NC}"
    python3 -m venv venv
fi

# Activate virtual environment
echo -e "${YELLOW}Activating virtual environment...${NC}"
source venv/bin/activate

# Install dependencies
echo -e "${YELLOW}Installing Python dependencies...${NC}"
pip install -q --upgrade pip
pip install -q -e .

# Start backend in background
echo -e "${YELLOW}Starting FastAPI backend on port 8000...${NC}"
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 > backend.log 2>&1 &
BACKEND_PID=$!
echo $BACKEND_PID > .backend.pid

wait_for_service 8000 "Backend"

# ============================================
# FRONTEND SERVICE
# ============================================

echo -e "\n${BLUE}========================================${NC}"
echo -e "${BLUE}Starting Frontend Service${NC}"
echo -e "${BLUE}========================================${NC}"

# Check if frontend directory exists
if [ ! -d "frontend" ]; then
    echo -e "${YELLOW}Frontend not initialized. Run implementation first.${NC}"
    echo -e "${YELLOW}This script will start backend only.${NC}"
else
    # Install frontend dependencies if needed
    if [ ! -d "frontend/node_modules" ]; then
        echo -e "${YELLOW}Installing npm dependencies...${NC}"
        cd frontend
        npm install
        cd ..
    fi

    # Start frontend in background
    echo -e "${YELLOW}Starting Vite frontend on port 3001...${NC}"
    cd frontend
    npm run dev -- --port 3001 > ../frontend.log 2>&1 &
    FRONTEND_PID=$!
    cd ..
    echo $FRONTEND_PID > .frontend.pid

    wait_for_service 3001 "Frontend"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo -e "${GREEN}========================================"
echo "Environment Ready!"
echo -e "========================================${NC}"
echo ""
echo -e "${BLUE}Services:${NC}"
echo -e "  Backend:  ${GREEN}http://localhost:8000${NC}"
echo -e "  Frontend: ${GREEN}http://localhost:3001${NC}"
echo ""
echo -e "${BLUE}API Documentation:${NC}"
echo -e "  Swagger: ${GREEN}http://localhost:8000/docs${NC}"
echo -e "  ReDoc:   ${GREEN}http://localhost:8000/redoc${NC}"
echo ""
echo -e "${BLUE}Process IDs:${NC}"
echo -e "  Backend:  $BACKEND_PID (saved to .backend.pid)"
if [ -f ".frontend.pid" ]; then
    echo -e "  Frontend: $FRONTEND_PID (saved to .frontend.pid)"
fi
echo ""
echo -e "${YELLOW}To stop services:${NC}"
echo -e "  kill \$(cat .backend.pid)"
if [ -f ".frontend.pid" ]; then
    echo -e "  kill \$(cat .frontend.pid)"
fi
echo ""
echo -e "${YELLOW}To view logs:${NC}"
echo -e "  tail -f backend.log"
if [ -f "frontend.log" ]; then
    echo -e "  tail -f frontend.log"
fi
echo ""
